#!/usr/bin/env python
"""
Multi-view pose fusion: combines left and right FoundationPose tracking results
into a single pose sequence in the left-camera coordinate frame.

PREREQUISITE — these must already exist on disk (generated by run_fp_track.py):
    foundationpose_v2/run/ob_in_cam/*.txt       (from: run_fp_track.py --camera left)
    foundationpose_v2/run_right/ob_in_cam/*.txt (from: run_fp_track.py --camera right)

This script does NOT run FoundationPose — it only reads the pose files above and fuses them.

Input:
    foundationpose_v2/run/ob_in_cam/*.txt         (left-camera poses)
    foundationpose_v2/run_right/ob_in_cam/*.txt   (right-camera poses)
    calib.json                                    (baseline_m)
    ffs/cam_K.txt                                 (intrinsics, for --vis only)

Output:
    foundationpose_v2/fused/ob_in_cam/*.txt       (fused poses, left-cam frame)
    foundationpose_v2/fused/track_vis/*.png       (--vis: mesh render + box + axis)
    foundationpose_v2/fused/video_frames/*.png    (--vis: RGB overlay + box + axis)

Usage:
    # Fusion only (no GPU needed)
    python scripts/run_fusion.py --clip clip03

    # Fusion + visualization (needs FoundationPose Docker container)
    python scripts/run_fusion.py --clip clip03 --vis

    # With outlier rejection + Gaussian temporal smoothing (recommended)
    python scripts/run_fusion.py --clip clip03 --method average --smooth 7 --vis

    # Tighter outlier thresholds (reject right frame if L-R diff > 3cm or > 15deg)
    python scripts/run_fusion.py --clip clip03 --outlier_trans 0.03 --outlier_rot 15

    # Ablation: left-only baseline
    python scripts/run_fusion.py --clip clip03 --method left_only --vis

    # Disable outlier rejection (use all right frames)
    python scripts/run_fusion.py --clip clip03 --no_outlier --vis
"""

import argparse, os, sys, json, glob, logging

code_dir = os.path.dirname(os.path.realpath(__file__))
repo_dir = os.path.dirname(code_dir)

import numpy as np
import cv2


# ---------------------------------------------------------------------------
# Pure-numpy rotation (replaces scipy.spatial.transform.Rotation)
# ---------------------------------------------------------------------------

class Rotation:
    """Minimal pure-numpy Rotation class (drop-in for scipy.spatial.transform.Rotation)."""

    def __init__(self, quat):
        self._q = np.asarray(quat, dtype=np.float64)

    @classmethod
    def from_matrix(cls, mat):
        """3x3 rotation matrix -> Rotation."""
        m = np.asarray(mat, dtype=np.float64)
        trace = np.trace(m)
        if trace > 0:
            s = np.sqrt(trace + 1.0) * 2.0
            w = 0.25 * s
            x = (m[2, 1] - m[1, 2]) / s
            y = (m[0, 2] - m[2, 0]) / s
            z = (m[1, 0] - m[0, 1]) / s
        elif m[0, 0] > m[1, 1] and m[0, 0] > m[2, 2]:
            s = np.sqrt(1.0 + m[0, 0] - m[1, 1] - m[2, 2]) * 2.0
            w = (m[2, 1] - m[1, 2]) / s
            x = 0.25 * s
            y = (m[0, 1] + m[1, 0]) / s
            z = (m[0, 2] + m[2, 0]) / s
        elif m[1, 1] > m[2, 2]:
            s = np.sqrt(1.0 + m[1, 1] - m[0, 0] - m[2, 2]) * 2.0
            w = (m[0, 2] - m[2, 0]) / s
            x = (m[0, 1] + m[1, 0]) / s
            y = 0.25 * s
            z = (m[1, 2] + m[2, 1]) / s
        else:
            s = np.sqrt(1.0 + m[2, 2] - m[0, 0] - m[1, 1]) * 2.0
            w = (m[1, 0] - m[0, 1]) / s
            x = (m[0, 2] + m[2, 0]) / s
            y = (m[1, 2] + m[2, 1]) / s
            z = 0.25 * s
        return cls([x, y, z, w])

    @classmethod
    def from_quat(cls, q):
        """Quaternion [x,y,z,w] -> Rotation."""
        return cls(q)

    def as_quat(self):
        """Return [x, y, z, w]."""
        return self._q.copy()

    def as_matrix(self):
        """Return 3x3 rotation matrix."""
        x, y, z, w = self._q
        return np.array([
            [1 - 2*y*y - 2*z*z,     2*x*y - 2*z*w,     2*x*z + 2*y*w],
            [    2*x*y + 2*z*w, 1 - 2*x*x - 2*z*z,     2*y*z - 2*x*w],
            [    2*x*z - 2*y*w,     2*y*z + 2*x*w, 1 - 2*x*x - 2*y*y],
        ], dtype=np.float64)


R = Rotation  # alias, same interface as scipy

# ---------------------------------------------------------------------------
# Coordinate transform
# ---------------------------------------------------------------------------

def build_left_from_right(baseline_m):
    """Right camera -> left camera transform for rectified stereo.

    In rectified stereo the right camera is at [baseline, 0, 0] in the
    left-camera frame.  Hence T_left_from_right = translate(+baseline, 0, 0).
    """
    T = np.eye(4)
    T[0, 3] = baseline_m
    return T


# ---------------------------------------------------------------------------
# IO helpers
# ---------------------------------------------------------------------------

def load_poses(txt_dir, id_strs):
    """Load 4x4 pose matrices from a directory of .txt files.

    Returns (poses, missing_ids).
    """
    N = len(id_strs)
    poses = np.zeros((N, 4, 4), dtype=np.float64)
    missing = np.zeros(N, dtype=bool)
    for i, sid in enumerate(id_strs):
        path = os.path.join(txt_dir, f'{sid}.txt')
        if os.path.exists(path):
            poses[i] = np.loadtxt(path).reshape(4, 4)
        else:
            missing[i] = True
    return poses, missing


def save_poses(txt_dir, id_strs, poses):
    """Save 4x4 poses as .txt files."""
    os.makedirs(txt_dir, exist_ok=True)
    for i, sid in enumerate(id_strs):
        np.savetxt(os.path.join(txt_dir, f'{sid}.txt'), poses[i].reshape(4, 4))


# ---------------------------------------------------------------------------
# Pose fusion
# ---------------------------------------------------------------------------

def _copy_available(poses_left_i, poses_right_i):
    """Return whichever of left/right has a non-zero pose."""
    if not np.all(poses_left_i == 0):
        return poses_left_i.copy()
    return poses_right_i.copy()


def _rotation_diff_deg(R_l, R_r):
    """Angular distance between two 3x3 rotation matrices, in degrees."""
    dR = R_l.T @ R_r
    cos = (np.trace(dR) - 1.0) / 2.0
    cos = np.clip(cos, -1.0, 1.0)
    return float(np.degrees(np.arccos(cos)))


def _mean_rotation(r_l, r_r):
    """Quaternion average with sign-disambiguation."""
    q_l = r_l.as_quat()
    q_r = r_r.as_quat()
    if np.dot(q_l, q_r) < 0:
        q_r = -q_r
    q = q_l + q_r
    q /= np.linalg.norm(q)
    return R.from_quat(q)


def fuse_average(poses_left, poses_right, valid):
    """Equal-weight fusion: quaternion-mean rotation, arithmetic-mean translation."""
    N = len(valid)
    fused = np.zeros((N, 4, 4), dtype=np.float64)
    for i in range(N):
        if not valid[i]:
            fused[i] = _copy_available(poses_left[i], poses_right[i])
            continue

        r_l = R.from_matrix(poses_left[i, :3, :3])
        r_r = R.from_matrix(poses_right[i, :3, :3])
        r_fused = _mean_rotation(r_l, r_r)
        t_fused = (poses_left[i, :3, 3] + poses_right[i, :3, 3]) / 2.0

        fused[i, :3, :3] = r_fused.as_matrix()
        fused[i, :3, 3] = t_fused
        fused[i, 3, 3] = 1.0
    return fused


def fuse_left_main(poses_left, poses_right, valid,
                   trans_thresh=0.02, rot_thresh_deg=10.0):
    """Left-main fusion: use left by default, average only when left and right agree.

    If translation diff < trans_thresh (m) AND rotation diff < rot_thresh_deg,
    fall through to average.  Otherwise keep left unchanged.
    """
    N = len(valid)
    fused = np.zeros((N, 4, 4), dtype=np.float64)
    n_avg, n_left = 0, 0
    for i in range(N):
        if not valid[i]:
            fused[i] = _copy_available(poses_left[i], poses_right[i])
            continue

        t_l = poses_left[i, :3, 3]
        t_r = poses_right[i, :3, 3]
        trans_diff = float(np.linalg.norm(t_l - t_r))
        rot_diff = _rotation_diff_deg(poses_left[i, :3, :3], poses_right[i, :3, :3])

        if trans_diff < trans_thresh and rot_diff < rot_thresh_deg:
            r_l = R.from_matrix(poses_left[i, :3, :3])
            r_r = R.from_matrix(poses_right[i, :3, :3])
            r_fused = _mean_rotation(r_l, r_r)
            t_fused = (t_l + t_r) / 2.0
            fused[i, :3, :3] = r_fused.as_matrix()
            fused[i, :3, 3] = t_fused
            n_avg += 1
        else:
            fused[i] = poses_left[i].copy()
            n_left += 1

        fused[i, 3, 3] = 1.0

    logging.info(f"  left_main: {n_avg} averaged, {n_left} left-only "
                 f"(thresholds: trans<{trans_thresh:.3f}m, rot<{rot_thresh_deg:.0f}deg)")
    return fused


# ---------------------------------------------------------------------------
# Outlier detection
# ---------------------------------------------------------------------------

def detect_outliers(poses_left, poses_right, valid,
                    trans_thresh=0.05, rot_thresh_deg=30.0):
    """Mark frames where right tracking likely failed as invalid.

    A frame is an outlier if left-right translation diff > trans_thresh (m)
    OR left-right rotation diff > rot_thresh_deg.

    Returns (valid_out, n_outliers).
    """
    valid_out = valid.copy()
    n_outliers = 0
    diffs = []
    for i in range(len(valid)):
        if not valid[i]:
            continue
        t_diff = float(np.linalg.norm(poses_left[i, :3, 3] - poses_right[i, :3, 3]))
        r_diff = _rotation_diff_deg(poses_left[i, :3, :3], poses_right[i, :3, :3])
        diffs.append((t_diff, r_diff))
        if t_diff > trans_thresh or r_diff > rot_thresh_deg:
            valid_out[i] = False
            n_outliers += 1

    diffs = np.array(diffs) if diffs else np.zeros((0, 2))
    if len(diffs) > 0:
        logging.info(f"  Outlier check: {n_outliers}/{len(diffs)} frames rejected "
                     f"(trans>{trans_thresh*1000:.0f}mm | rot>{rot_thresh_deg:.0f}deg)")
        logging.info(f"  L-R stats (valid frames): "
                     f"trans median={np.median(diffs[:,0])*1000:.1f}mm "
                     f"max={diffs[:,0].max()*1000:.1f}mm | "
                     f"rot median={np.median(diffs[:,1]):.1f}deg "
                     f"max={diffs[:,1].max():.1f}deg")
    return valid_out


# ---------------------------------------------------------------------------
# Temporal smoothing
# ---------------------------------------------------------------------------

def _gaussian_kernel(size, sigma=None):
    """1D Gaussian kernel."""
    if sigma is None:
        sigma = size / 4.0
    x = np.arange(size) - (size - 1) / 2.0
    k = np.exp(-0.5 * (x / sigma) ** 2)
    return k / k.sum()


def smooth_poses(poses, window=5, method='gaussian'):
    """Smooth a pose sequence in quaternion + translation space.

    Args:
        window: kernel size (odd)
        method: 'moving_avg' (uniform) or 'gaussian' (Gaussian-weighted, default)
    """
    if window <= 1:
        return poses.copy()

    if window % 2 == 0:
        window += 1

    N = poses.shape[0]
    quats = np.zeros((N, 4))
    trans = np.zeros((N, 3))
    for i in range(N):
        quats[i] = R.from_matrix(poses[i, :3, :3]).as_quat()
        trans[i] = poses[i, :3, 3]

    for i in range(1, N):
        if np.dot(quats[i], quats[i - 1]) < 0:
            quats[i] = -quats[i]

    if method == 'gaussian':
        kernel = _gaussian_kernel(window)
    else:
        kernel = np.ones(window) / window

    half = window // 2
    smoothed_quat = np.zeros_like(quats)
    smoothed_trans = np.zeros_like(trans)

    for i in range(N):
        lo = max(0, i - half)
        hi = min(N, i + half + 1)
        k_lo = half - (i - lo)
        k_hi = half + (hi - i)
        k = kernel[k_lo:k_hi]
        k = k / k.sum()
        smoothed_quat[i] = (quats[lo:hi].T @ k).T
        smoothed_trans[i] = (trans[lo:hi].T @ k).T

    norms = np.linalg.norm(smoothed_quat, axis=1, keepdims=True)
    smoothed_quat /= norms

    smoothed = poses.copy()
    for i in range(N):
        smoothed[i, :3, :3] = R.from_quat(smoothed_quat[i]).as_matrix()
        smoothed[i, :3, 3] = smoothed_trans[i]
    return smoothed


# ---------------------------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------------------------

def print_stats(poses_left, poses_right, fused, valid):
    """Print per-frame comparison statistics."""
    diffs_LR, diffs_LF = [], []
    for i in range(len(valid)):
        if not valid[i]:
            continue
        t_l = poses_left[i, :3, 3]
        t_r = poses_right[i, :3, 3]
        t_f = fused[i, :3, 3]
        diffs_LR.append(np.linalg.norm(t_l - t_r))
        diffs_LF.append(np.linalg.norm(t_l - t_f))

    diffs_LR = np.array(diffs_LR)
    diffs_LF = np.array(diffs_LF)
    logging.info(f"Frames: {len(valid)} total, {valid.sum()} fused, "
                 f"{(~valid).sum()} missing on one side")
    logging.info(f"Left <-> Right translation discrepancy (mm): "
                 f"mean={diffs_LR.mean()*1000:.1f}  max={diffs_LR.max()*1000:.1f}")
    logging.info(f"Left <-> Fused translation discrepancy (mm): "
                 f"mean={diffs_LF.mean()*1000:.1f}  max={diffs_LF.max()*1000:.1f}")


# ---------------------------------------------------------------------------
# Visualization (requires FoundationPose + CUDA)
# ---------------------------------------------------------------------------

def _try_import_fp():
    """Try importing FoundationPose rendering modules.  Returns (ok, modules_dict)."""
    try:
        sys.path.insert(0, os.path.join(repo_dir, 'FoundationPose'))
        import estimater
        import trimesh
        import torch
        import nvdiffrast.torch as dr
        import imageio
        return True, {
            'estimater': estimater, 'trimesh': trimesh,
            'torch': torch, 'dr': dr, 'imageio': imageio,
        }
    except ImportError as e:
        logging.warning(f"Cannot import FoundationPose / CUDA modules: {e}")
        logging.warning("Visualization disabled. Run inside the FP Docker container for --vis.")
        return False, {}


def generate_vis(data_dir, id_strs, fused_poses, args):
    """Generate track_vis and video_frames for fused poses.

    Mirrors the debug=2 rendering from run_fp_track.py.
    """
    ok, m = _try_import_fp()
    if not ok:
        return

    estimater = m['estimater']
    trimesh = m['trimesh']
    torch = m['torch']
    dr_mod = m['dr']
    imageio = m['imageio']

    # ---- mesh ----
    mesh_file = os.path.join(data_dir, 'mesh', 'clean_mesh.obj')
    if not os.path.exists(mesh_file):
        logging.warning(f"Mesh not found: {mesh_file}")
        return

    scale_file = os.path.join(data_dir, 'foundationpose', 'run', 'scales', 'unified_scale.txt')
    mesh_scale = float(open(scale_file).read().strip()) if os.path.exists(scale_file) else 1.0
    logging.info(f"[vis] Mesh scale: {mesh_scale}")

    mesh = trimesh.load(mesh_file)
    mesh.vertices = mesh.vertices * mesh_scale
    to_origin, extents = trimesh.bounds.oriented_bounds(mesh)
    bbox = np.stack([-extents / 2, extents / 2], axis=0).reshape(2, 3)

    # ---- intrinsics & image resolution ----
    K_path = os.path.join(data_dir, 'ffs', 'cam_K.txt')
    K_full = np.loadtxt(K_path).reshape(3, 3)

    rgb_dir = os.path.join(data_dir, 'rgb')
    sample_img = cv2.imread(os.path.join(rgb_dir, f'{id_strs[0]}.jpg'))
    if sample_img is None:
        sample_img = cv2.imread(os.path.join(rgb_dir, f'{id_strs[0]}.png'))
    H_orig, W_orig = sample_img.shape[:2]

    shorter_side = args.shorter_side
    downscale = shorter_side / min(H_orig, W_orig)
    H, W = int(H_orig * downscale), int(W_orig * downscale)
    K = K_full.copy()
    K[:2] *= downscale

    # ---- FoundationPose (minimal, for mesh_tensors + glctx) ----
    scorer = estimater.ScorePredictor()
    refiner = estimater.PoseRefinePredictor()
    glctx = dr_mod.RasterizeCudaContext()
    est = estimater.FoundationPose(
        model_pts=mesh.vertices, model_normals=mesh.vertex_normals,
        mesh=mesh, scorer=scorer, refiner=refiner,
        debug_dir=os.path.join(data_dir, 'foundationpose_v2', 'fused'),
        debug=0, glctx=glctx,
    )
    logging.info("[vis] FoundationPose renderer ready")

    # ---- render each frame ----
    out_vis = os.path.join(data_dir, 'foundationpose_v2', 'fused', 'track_vis')
    out_vf = os.path.join(data_dir, 'foundationpose_v2', 'fused', 'video_frames')
    os.makedirs(out_vis, exist_ok=True)
    os.makedirs(out_vf, exist_ok=True)

    n_skipped = 0
    for i, sid in enumerate(id_strs):
        pose = fused_poses[i]

        # --- validate pose ---
        if np.all(pose == 0) or not np.isfinite(pose).all():
            logging.warning(f"[vis] Frame {sid}: degenerate pose, skip")
            n_skipped += 1
            continue

        R_mat = pose[:3, :3]
        det = np.linalg.det(R_mat)
        if abs(det - 1.0) > 0.5:
            logging.warning(f"[vis] Frame {sid}: det(R)={det:.3f} (expected ~1), skip")
            n_skipped += 1
            continue

        if pose[2, 3] <= 0.01:
            logging.warning(f"[vis] Frame {sid}: z={pose[2,3]:.4f}m <= 0.01, skip")
            n_skipped += 1
            continue

        # Read + resize left RGB
        rgb_path = os.path.join(rgb_dir, f'{sid}.jpg')
        if not os.path.exists(rgb_path):
            rgb_path = os.path.join(rgb_dir, f'{sid}.png')
        color = cv2.imread(rgb_path)
        if color is None:
            logging.warning(f"[vis] Frame {sid}: cannot read RGB, skip")
            n_skipped += 1
            continue
        color = cv2.resize(color, (W, H), interpolation=cv2.INTER_NEAREST)

        center_pose = pose @ np.linalg.inv(to_origin)

        try:
            # --- track_vis: black-background mesh render ---
            H8 = (H + 7) // 8 * 8
            W8 = (W + 7) // 8 * 8
            K8 = K.copy()
            K8[0] *= W8 / W
            K8[1] *= H8 / H

            ob_in_cam_t = torch.as_tensor(pose, device='cuda', dtype=torch.float).reshape(1, 4, 4)
            rendered, _, _ = estimater.nvdiffrast_render(
                K=K8, H=H8, W=W8,
                ob_in_cams=ob_in_cam_t, glctx=est.glctx,
                mesh_tensors=est.mesh_tensors, mesh=mesh,
            )
            rendered_np = (rendered[0].data.cpu().numpy() * 255).astype(np.uint8)
            rendered_np = rendered_np[:H, :W, :3].copy()

            vis_track = estimater.draw_posed_3d_box(K, img=rendered_np, ob_in_cam=center_pose, bbox=bbox)
            vis_track = estimater.draw_xyz_axis(vis_track, ob_in_cam=center_pose, scale=0.1,
                                                K=K, thickness=3, transparency=0, is_input_rgb=True)
            imageio.imwrite(os.path.join(out_vis, f'{sid}.png'), vis_track)

            # --- video_frames: RGB overlay ---
            vis_rgb = estimater.draw_posed_3d_box(K, img=color.copy(), ob_in_cam=center_pose, bbox=bbox)
            vis_rgb = estimater.draw_xyz_axis(vis_rgb, ob_in_cam=center_pose, scale=0.1,
                                              K=K, thickness=3, transparency=0, is_input_rgb=True)
            imageio.imwrite(os.path.join(out_vf, f'{sid}.png'), vis_rgb[..., ::-1])  # BGR->RGB

        except Exception as e:
            logging.warning(f"[vis] Frame {sid}: render failed ({e}), skip")
            n_skipped += 1
            continue

        if (i + 1) % 50 == 0:
            logging.info(f"[vis] {i + 1}/{len(id_strs)} frames rendered")

    logging.info(f"[vis] Done: {len(id_strs) - n_skipped} rendered, "
                 f"{n_skipped} skipped -> {out_vis}/  +  {out_vf}/")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='Multi-view pose fusion for stereo FoundationPose')
    parser.add_argument('--clip', type=str, default='clip03')
    parser.add_argument('--method', type=str, default='average',
                        choices=['average', 'left_main', 'left_only', 'right_only'],
                        help='Fusion strategy (default: average)')
    parser.add_argument('--outlier_trans', type=float, default=0.05,
                        help='Reject right frame if L-R translation diff > this (m; default: 0.05=5cm)')
    parser.add_argument('--outlier_rot', type=float, default=30.0,
                        help='Reject right frame if L-R rotation diff > this (deg; default: 30)')
    parser.add_argument('--no_outlier', action='store_true',
                        help='Disable outlier rejection')
    parser.add_argument('--smooth', type=int, default=0,
                        help='Temporal smoothing window (odd; 0=off; e.g. 5)')
    parser.add_argument('--smooth_method', type=str, default='gaussian',
                        choices=['gaussian', 'moving_avg'],
                        help='Smoothing kernel (default: gaussian)')
    parser.add_argument('--vis', action='store_true',
                        help='Generate track_vis + video_frames (requires FoundationPose/CUDA)')
    parser.add_argument('--shorter_side', type=int, default=800,
                        help='Resize shorter side for vis rendering (default: 800)')
    parser.add_argument('--start_frame', type=int, default=0)
    parser.add_argument('--end_frame', type=int, default=-1)
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format='%(asctime)s %(message)s')

    data_dir = os.path.join(repo_dir, 'data', args.clip)
    left_dir = os.path.join(data_dir, 'foundationpose_v2', 'run', 'ob_in_cam')
    right_dir = os.path.join(data_dir, 'foundationpose_v2', 'run_right', 'ob_in_cam')
    out_dir = os.path.join(data_dir, 'foundationpose_v2', 'fused', 'ob_in_cam')

    # ----- calibration -----
    calib_path = os.path.join(data_dir, 'calib.json')
    with open(calib_path) as f:
        calib = json.load(f)
    baseline_m = float(calib['baseline_m'])
    logging.info(f"Baseline: {baseline_m * 1000:.2f} mm")

    T_left_from_right = build_left_from_right(baseline_m)

    # ----- frame list -----
    left_files = sorted(glob.glob(os.path.join(left_dir, '*.txt')))
    if not left_files:
        raise FileNotFoundError(f"No pose files in {left_dir}")
    id_strs = [os.path.splitext(os.path.basename(f))[0] for f in left_files]
    logging.info(f"Found {len(id_strs)} pose files in left directory")

    end = args.end_frame if args.end_frame > 0 else len(id_strs)
    id_strs = id_strs[args.start_frame:end]
    logging.info(f"Processing frames [{args.start_frame}, {end}) - {len(id_strs)} frames")

    # ----- load -----
    poses_left, miss_left = load_poses(left_dir, id_strs)
    poses_right_raw, miss_right = load_poses(right_dir, id_strs)

    poses_right = poses_right_raw.copy()
    for i in range(len(id_strs)):
        if not miss_right[i]:
            poses_right[i] = T_left_from_right @ poses_right_raw[i]

    valid = ~miss_left & ~miss_right

    # ----- outlier rejection -----
    if not args.no_outlier:
        logging.info(f"Outlier rejection: trans>{args.outlier_trans*1000:.0f}mm | rot>{args.outlier_rot:.0f}deg")
        valid = detect_outliers(poses_left, poses_right, valid,
                                trans_thresh=args.outlier_trans,
                                rot_thresh_deg=args.outlier_rot)

    # ----- fuse -----
    if args.method == 'average':
        fused = fuse_average(poses_left, poses_right, valid)
    elif args.method == 'left_main':
        fused = fuse_left_main(poses_left, poses_right, valid)
    elif args.method == 'left_only':
        fused = poses_left.copy()
    elif args.method == 'right_only':
        fused = poses_right.copy()
    else:
        raise ValueError(f"Unknown method: {args.method}")

    print_stats(poses_left, poses_right, fused, valid)

    # ----- temporal smoothing -----
    if args.smooth > 0:
        logging.info(f"Temporal smoothing: window={args.smooth}, method={args.smooth_method}")
        fused = smooth_poses(fused, window=args.smooth, method=args.smooth_method)

    # ----- save poses -----
    save_poses(out_dir, id_strs, fused)
    logging.info(f"Saved {len(id_strs)} fused poses -> {out_dir}")

    # ----- visualization -----
    if args.vis:
        generate_vis(data_dir, id_strs, fused, args)


if __name__ == '__main__':
    main()
